server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: ${JDBC_URL:${SPRING_DATASOURCE_URL:jdbc:h2:mem:orders_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}}
    username: ${DB_USER:${SPRING_DATASOURCE_USERNAME:sa}}
    password: ${DB_PASS:${SPRING_DATASOURCE_PASSWORD:}}
    driver-class-name: ${DB_DRIVER:${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
